Repository Java-and-Script/pickple-front, pull requests merged in 2023-12, with the labels that each got.

#429 알림 수신 시 관련된 쿼리들 무효화하는 기능
  src/ConnectSSE.tsx
Labels: 기능, D-0

#433 react hot toast 이용해 커스텀 토스터 구현
  src/ConnectSSE.tsx
  src/CustomToaster.tsx
  src/pages/NotificationPage/components/CrewNotificationItem/CrewNotificationItem.tsx
  src/pages/__components__/ItemListPageSkeleton/ItemListPageSkeleton.tsx
  src/routes/ToastResume.tsx
  src/routes/router.tsx
  src/type/models/Alarm.ts
Labels: 기능

#436 웹뷰 페이지 작성
  src/App.tsx
  src/assets/chatSample.png
  src/assets/githubIcon.svg
  src/assets/homeSample.png
  src/assets/mapSample.png
  src/assets/notionIcon.svg
  src/assets/qrIcon.png
  src/assets/webView/solvingProblem/filter.svg
  src/assets/webView/solvingProblem/lock.svg
  src/assets/webView/solvingProblem/smile.svg
  src/assets/webView/solvingProblem/thumbUp.svg
  src/assets/webView/techStack/back/awsEc2.png
  src/assets/webView/techStack/back/awsElastiCache.png
  src/assets/webView/techStack/back/awsRds.png
  src/assets/webView/techStack/back/docker.png
  src/assets/webView/techStack/back/githubActions.png
  src/assets/webView/techStack/back/java17.png
  src/assets/webView/techStack/back/jpa.png
  src/assets/webView/techStack/back/mySql.png
  src/assets/webView/techStack/back/nginx.png
  src/assets/webView/techStack/back/redis.png
  src/assets/webView/techStack/back/springBoot.png
  src/assets/webView/techStack/front/axios.png
  src/assets/webView/techStack/front/emotion.png
  src/assets/webView/techStack/front/eslint.png
  src/assets/webView/techStack/front/figma.png
  src/assets/webView/techStack/front/githubActions.png
  src/assets/webView/techStack/front/npm.png
  src/assets/webView/techStack/front/prettier.png
  src/assets/webView/techStack/front/react.png
  src/assets/webView/techStack/front/reactHookForm.png
  src/assets/webView/techStack/front/reactRouterDom.svg
  src/assets/webView/techStack/front/tanstackQuery.png
  src/assets/webView/techStack/front/typeScript.png
  src/assets/webView/techStack/front/vercel.png
  src/assets/webView/techStack/front/vite.png
  src/assets/webView/techStack/front/zustand.png
  src/pages/WebViewPage/WebViewPage.tsx
  src/styles/globalStyle.tsx
Labels: 기능, D-0

#446 FOUT(Flash of Invisible Text) 문제
  index.html
  src/components/MatchItem/components/BottomButton/BottomButton.styles.ts
  src/components/Modal/Modal.tsx
  src/pages/MapPage/MatchItem/components/BottomButton/BottomButton.styles.ts
  src/styles/globalStyle.tsx
Labels: 긴급, 버그, D-0

#454 채팅방 페이지에서 페이지 이동 시 스크롤이 안 먹는 버그
  src/hooks/chats/useAllChatRoomListQuery.ts
  src/pages/ChattingPage/hooks/useChattingPage.ts
Labels: 긴급, 버그

#458 채팅 전송 버튼 아이콘으로 변경
  src/assets/paperPlane.svg
  src/pages/ChattingPage/ChattingPage.style.ts
  src/pages/ChattingPage/ChattingPage.tsx
  src/pages/ChattingPage/skeletons/ChattingPageSkeleton.tsx
Labels: 긴급, 버그

#463 추후 업데이트 기능 안내 토스트
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/AllServicesPage/hooks/useAllServicesPage.ts
  src/pages/ProfilePage/components/Profile.tsx
  src/pages/ProfilePage/hooks/useProfile.ts
Labels: 긴급, 기타

#460 토글 버튼 스타일 수정
  src/components/shared/ToggleButton/ToggleButton.style.ts
Labels: 긴급, 스타일링

#464 전체서비스 페이지에 근처게스트모집, 추천크루 탭 추가
  src/assets/foot.svg
  src/assets/star.svg
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/CreatePage/CreatePage.tsx
  src/pages/CreatePage/components/CreatePageCard.tsx
  src/pages/CrewsDetailPage/CrewsDetailPage.loading.tsx
Labels: 기능

#467 변경된 토글버튼 훅 반영
  src/components/SelectPosition/SelectPosition.tsx
Labels: 긴급, 버그

#474 메인 페이지 버튼 디자인 변경
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/skeletons/MainPageSkeleton.tsx
Labels: 긴급

#476 convertUTCToKoreanTime 적용 해제
  src/components/NotificationItem/NotificationItem.tsx
  src/pages/ChatRoomListPage/components/ChatRoomItem.tsx
  src/pages/ChattingPage/components/Chat.tsx
  src/pages/ChattingPage/hooks/useChattingPage.ts
  src/pages/ChattingPage/services/formatDate.ts
  src/pages/NotificationPage/components/GameNotificationItem/getGameNotificationTitle.ts
  src/utils/convertUTCToKoreanTime.ts
Labels: 긴급

#481 게스트 모집 상세 페이지 경기 소개 수정
  src/pages/CrewsDetailPage/CrewsDetailPage.styles.ts
  src/pages/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
Labels: 긴급, D-0

#484 지도 페이지 내 게스트 모집 상세의 경기 소개 수정
  src/pages/MapPage/components/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/MapPage/components/GamesDetailPage/GamesDetailPage.tsx
Labels: 긴급, D-0

#485 지도 페이지 애니메이션 위치 수정
  src/pages/MapPage/MapPage.style.ts
Labels: 긴급, 스타일링

#487 크루 상세 페이지 크루 소개글 수정
  src/pages/CrewsDetailPage/CrewsDetailPage.styles.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
Labels: 긴급, D-0

#489 알림 수신 시 가입, 참여여부 쿼리 무효화 기능
  src/ConnectSSE.tsx
Labels: 기능, D-0

#493 웹뷰에서 모바일뷰 볼 수 있는 버튼 구현
  src/pages/WebViewPage/WebViewPage.tsx
Labels: 기능

#495 sse 연결 오류 시 3초마다 다시 연결하도록 수정
  src/ConnectSSE.tsx
  src/hooks/useEventSource.ts
Labels: 긴급, 버그

#498 refactor: 노션 아이콘 주소 변경
  src/pages/WebViewPage/WebViewPage.tsx
Labels: 리팩터링
