Repository Java-and-Script/pickple-front, pull requests merged in 2023-10, with the labels that each got.

#13 깃허브 액션을 활용한 리뷰어 자동 할당 기능 추가
  .github/workflows/pick-random-reviewer.yml
Labels: 긴급

#10 .env 환경변수로 MSW 사용여부 결정
  .gitignore
  package.json
  src/main.tsx
  src/mocks/server.ts
  src/pages/HomePage.tsx
  tests/pages/HomePage.spec.tsx
  tests/setup.ts
Labels: 기능

#17 프로젝트에 필요한 svg 파일 추가
  src/assets/ball.svg
  src/assets/bell.svg
  src/assets/chat.svg
  src/assets/close.svg
  src/assets/crewManage.svg
  src/assets/crewMember.svg
  src/assets/exit.svg
  src/assets/follow.svg
  src/assets/gameMember.svg
  src/assets/hamburger.svg
  src/assets/heart.svg
  src/assets/home.svg
  src/assets/leftArrow.svg
  src/assets/map.svg
  src/assets/medal.svg
  src/assets/money.svg
  src/assets/pen.svg
  src/assets/plus.svg
  src/assets/profile.svg
  src/assets/rightArrow.svg
  src/assets/search.svg
  src/assets/social.svg
  src/assets/whistle.svg
Labels: 기타

#15 라우트 정의 및 레이아웃 컴포넌트 작성
  src/App.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/index.ts
  src/pages/Layout.tsx
  src/routes/router.tsx
Labels: 기능

#18 글로벌 스타일 설정
  index.html
  src/App.tsx
  src/styles/emotion.d.ts
  src/styles/globalStyle.tsx
Labels: 스타일링

#31 하단 navbar 구현
  src/components/shared/Navbar/Navbar.style.ts
  src/components/shared/Navbar/Navbar.tsx
  src/components/shared/Navbar/index.ts
  src/pages/Layout.tsx
Labels: 기능, D-2

#36 헤더 컴포넌트 구현
  src/components/shared/Header/Header.style.ts
  src/components/shared/Header/Header.tsx
  src/components/shared/Header/index.ts
Labels: 기능, D-2

#20 Text 공통 컴포넌트 구현
  src/components/shared/Text/Text.styles.ts
  src/components/shared/Text/Text.tsx
  src/components/shared/Text/index.ts
Labels: 기능

#30 MatchItem 공통 컴포넌트 구현
  src/components/shared/MatchItem/MatchItem.styles.ts
  src/components/shared/MatchItem/MatchItem.tsx
  src/components/shared/MatchItem/index.ts
  src/consts/weekday.ts
  src/pages/Layout.tsx
  src/styles/globalStyle.tsx
Labels: 기능

#26 공통 버튼 컴포넌트 추가
  src/components/shared/Button/Button.styles.ts
  src/components/shared/Button/Button.tsx
  src/components/shared/Button/index.ts
  src/styles/button.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 기능, D-2

#43 virtual scroll component (드르륵) 구현
  src/components/shared/VirtualScroll/VirtualScroll.styles.ts
  src/components/shared/VirtualScroll/VirtualScroll.tsx
  src/components/shared/VirtualScroll/index.ts
Labels: 기능, D-0

#33 ToggleButton 공통 컴포넌트 구현
  src/components/shared/ToggleButton/ToggleButton.style.ts
  src/components/shared/ToggleButton/ToggleButton.tsx
  src/components/shared/ToggleButton/ToggleButtons.hook.ts
  src/components/shared/ToggleButton/index.ts
Labels: 기능

#37 Input 공통 컴포넌트 구현
  src/components/shared/Input/Input.style.ts
  src/components/shared/Input/Input.tsx
  src/components/shared/Input/index.ts
Labels: 기능

#39 수락 카드 공통 컴포넌트 구현
  src/components/shared/AllowCard/AllowCard.style.ts
  src/components/shared/AllowCard/AllowCard.tsx
  src/components/shared/AllowCard/AllowCardGroup.tsx
  src/components/shared/AllowCard/index.ts
  src/components/shared/Button/Button.styles.ts
Labels: 기능

#42 Select box 공통 컴포넌트 구현
  src/components/shared/SelectBox/SelectBox.style.ts
  src/components/shared/SelectBox/SelectBox.tsx
  src/components/shared/SelectBox/index.ts
Labels: 기능

#49 Modal 공통 컴포넌트 구현
  package-lock.json
  package.json
  src/components/shared/Modal/Modal.styles.ts
  src/components/shared/Modal/Modal.tsx
  src/components/shared/Modal/index.ts
Labels: 기능, D-0

#53 MatchItem 공통 컴포넌트 수정
  src/components/shared/MatchItem/MatchItem.styles.ts
  src/components/shared/MatchItem/MatchItem.tsx
Labels: 기능, D-0

#56 hotfix: #51 공통 버튼 컴포넌트 수정
  src/components/shared/Button/Button.styles.ts
  src/components/shared/Button/Button.tsx
Labels: 긴급

#63 Feat/#58 navbar header refactoring
  index.html
  src/assets/logoSvg.svg
  src/components/shared/Header/Header.style.ts
  src/components/shared/Header/Header.tsx
  src/components/shared/Navbar/Navbar.style.ts
  src/components/shared/Navbar/Navbar.tsx
  src/pages/Layout.tsx
  src/styles/globalStyle.tsx
  src/styles/styles.ts
Labels: 긴급

#68 모델 타입 정의
  src/type/models/Authenticated.ts
  src/type/models/Crew.ts
  src/type/models/CrewProfile.ts
  src/type/models/Game.ts
  src/type/models/Member.ts
  src/type/models/MemberProfile.ts
  src/type/models/Position.ts
  src/type/models/Registration.ts
  src/type/models/index.ts
Labels: 기능, D-0
