Repository Java-and-Script/pickple-front, pull requests merged in 2023-11, with the labels that each got.

#69 Axios instance 구현
  package.json
  src/api/axiosInstance.ts
  src/api/index.ts
  src/api/interceptors.ts
  vercel.json
Labels: 기능, D-0

#60 로그인, 정보 입력 페이지 구현
  src/assets/kakao_login_large_wide.png
  src/assets/logo.png
  src/consts/positions.ts
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/index.ts
  src/pages/RegisterPage/RegisterPage.style.ts
  src/pages/RegisterPage/RegisterPage.tsx
  src/pages/RegisterPage/index.ts
  src/routes/router.tsx
  src/styles/button.ts
Labels: 기능

#57 내 근처 게스트 매치 페이지 구현
  src/components/shared/AvatarGroup/AvatarGroup.tsx
  src/components/shared/MatchItem/MatchItem.tsx
  src/consts/weekday.ts
  src/hooks/useHeaderTitle.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/GamesNearPage/GamesNearPage.styles.ts
  src/pages/GamesNearPage/GamesNearPage.tsx
  src/pages/GamesNearPage/index.ts
  src/routes/router.tsx
Labels: 기능, D-2

#59 경기 상세 페이지 구현
  src/api/getMatch.ts
  src/components/shared/Flex/Flex.ts
  src/components/shared/Flex/index.ts
  src/hooks/queries/useMatchQuery.ts
  src/pages/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/pages/GamesDetailPage/index.ts
  src/routes/router.tsx
Labels: 기능, D-2

#62 게스트 모집글 작성 페이지 구현
  package-lock.json
  public/mockServiceWorker.js
  src/components/shared/VirtualScroll/VirtualScroll.styles.ts
  src/components/shared/VirtualScroll/VirtualScroll.tsx
  src/pages/CreateGamePage/CreateGamePage.styles.ts
  src/pages/CreateGamePage/CreateGamePage.tsx
  src/pages/CreateGamePage/index.ts
  src/routes/router.tsx
Labels: 기능

#70 메인 페이지 구현
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/index.ts
  src/routes/router.tsx
Labels: 기능, D-2

#71 생성하기 페이지 구현
  src/pages/CreatePage/CreatePage.style.ts
  src/pages/CreatePage/CreatePage.tsx
  src/pages/CreatePage/index.ts
  src/routes/router.tsx
Labels: 기능, D-2

#61 관리(참여 승인) 페이지 구현
  src/components/shared/AllowCard/AllowCard.tsx
  src/pages/ManagePage/ManagePage.style.ts
  src/pages/ManagePage/ManagePage.tsx
  src/pages/ManagePage/index.ts
  src/routes/router.tsx
Labels: 기능

#72 Router conflict 해결
  src/pages/MainPage/MainPage.tsx
  src/routes/router.tsx
Labels: 긴급, D-0

#78 경기(매치) 관련 api 함수 구현
  src/api/games/deleteGameParticipate.ts
  src/api/games/getGameDetail.ts
  src/api/games/getGameMembers.ts
  src/api/games/getGames.ts
  src/api/games/patchGameParticipate.ts
  src/api/games/patchMannerScoreReview.ts
  src/api/games/postGame.ts
  src/api/games/postGameParticipate.ts
  src/hooks/mutations/useGameMutation.ts
  src/hooks/queries/useGamesQuery.ts
  src/mocks/data/game.ts
  src/mocks/handlers/game.ts
  src/type/api/games.ts
Labels: 기능, D-0

#84 회원 API, MSW 구현
  src/api/member/getConfirmedGames.ts
  src/api/member/getCreatedGames.ts
  src/api/member/getLogin.ts
  src/api/member/getMemberProfile.ts
  src/api/member/postRefreshAccessToken.ts
  src/api/member/postRegistration.ts
  src/hooks/mutations/useRefreshAccessTokenMutation.ts
  src/hooks/mutations/useRegistrationMutation.ts
  src/hooks/queries/useConfirmGamesQuery.ts
  src/hooks/queries/useCreatedGamesQuery.ts
  src/hooks/queries/useLoginQuery.ts
  src/hooks/queries/useMemberProfileQuery.ts
  src/mocks/data/member.ts
  src/mocks/handlers/member.ts
  src/type/api/member.ts
Labels: 기능, D-0

#80 게스트 모집글 상세보기 mock api 구현
  src/hooks/queries/useGameDetailQuery.ts
  src/mocks/handlers/game.ts
  src/type/api/error.ts
Labels: 기능

#82 게스트 모집에 참여 신청 혹은 확정된 사용자 정보 목록 조회 api mocking
  src/api/games/getGameMembers.ts
  src/hooks/queries/useGameMembersQuery.ts
  src/mocks/data/game.ts
  src/mocks/handlers/game.ts
Labels: 기능

#85 게스트 모집 참여 신청 api mocking
  src/api/games/patchGameParticipate.ts
  src/hooks/mutations/useGameParticipateCreateMutation.ts
  src/mocks/handlers/game.ts
Labels: 기능

#100 All-Service page 구현
  package-lock.json
  package.json
  src/pages/AllServicesPage/AllServicesPage.style.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/AllServicesPage/MenuItem.tsx
  src/pages/AllServicesPage/index.ts
  src/routes/router.tsx
  tsconfig.json
  vite.config.ts
Labels: 기능, D-1

#104 게스트 모집 참여 신청 API Mocking
  src/mocks/handlers/game.ts
Labels: 기능

#107 Login api mocking 수정
  src/api/interceptors.ts
  src/api/member/getConfirmedGames.ts
  src/hooks/queries/useConfirmGamesQuery.ts
  src/hooks/queries/useLoginQuery.ts
  src/mocks/data/member.ts
  src/mocks/handlers/member.ts
  src/pages/LoginPage/LoginPage.tsx
  src/type/api/member.ts
Labels: 긴급, D-0

#99 게스트 모집 생성 페이지 api 연동
  src/hooks/mutations/useGameParticipateDeleteMutation.ts
  src/hooks/mutations/useGameParticipatePatchMutation.ts
  src/hooks/mutations/useMannerScoreReviewPatchMutation.ts
  src/pages/CreateGamePage/CreateGamePage.tsx
  src/type/api/games.ts
  src/type/models/Game.ts
Labels: 기능

#111 게스트 매너스코어 리뷰 남기기 API Mocking
  src/mocks/handlers/game.ts
Labels: 기능

#117 게스트 모집 페이지 경기 날짜 선택 캘린더 구현
  package-lock.json
  package.json
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/index.ts
  src/components/SelectPosition/SelectPosition.tsx
  src/components/SelectPosition/index.ts
  src/pages/CreateGamePage/CreateGamePage.tsx
  src/utils/formatDate.ts
Labels: 기능

#102 내 근처 게스트 매치 페이지 api 연동
  src/components/shared/Image/Image.styles.ts
  src/hooks/queries/useGamesQuery.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/GamesNearPage/GamesNearPage.tsx
  src/routes/router.tsx
  src/utils/domain.ts
Labels: 기능

#124 hotfix: 매치 api mocking handler 수정
  src/mocks/handlers/game.ts
Labels: 긴급

#103 게스트 모집 상세 페이지 api 연동
  src/api/getMatch.ts
  src/hooks/queries/useMatchQuery.ts
  src/mocks/handlers/game.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
Labels: 기능

#108 메인페이지 api 연동
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/useMainPageNearGamesQuery.ts
  src/routes/router.tsx
Labels: 기능, D-2

#119 프로필 페이지 ui 구현 및 api 연동
  src/pages/ProfilePage/Profile.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/index.ts
  src/routes/router.tsx
Labels: 기능

#120 게스트 매치 참여 관리 페이지 api 연동
  src/components/AllowCard/AllowCard.style.ts
  src/components/AllowCard/AllowCard.tsx
  src/hooks/mutations/useAllowGameParticipateMutation.ts
  src/hooks/mutations/useDisallowGameParticipateMutation.ts
  src/pages/GamesManagePage/GamesManagePage.style.ts
  src/pages/GamesManagePage/GamesManagePage.tsx
  src/pages/GamesManagePage/index.ts
  src/pages/ManagePage/ManagePage.tsx
  src/pages/ManagePage/index.ts
  src/routes/router.tsx
Labels: 기능

#122 리뷰페이지 ui 구현
  src/pages/ReviewPage/ReviewPage.style.ts
  src/pages/ReviewPage/ReviewPage.tsx
  src/pages/ReviewPage/ToggleButton.style.ts
  src/pages/ReviewPage/ToggleButton.tsx
  src/pages/ReviewPage/ToggleButtons.hook.ts
  src/pages/ReviewPage/index.ts
  src/routes/router.tsx
  src/styles/button.ts
Labels: 긴급, 기능

#126 Image 컴포넌트 기본 이미지 렌더링 기능 추가, 로그인 정보 localStorage key값 변경
  src/assets/default.svg
  src/components/shared/Image/Image.styles.ts
  src/components/shared/Image/Image.tsx
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/pages/GamesHostPage/GamesHostPage.tsx
  src/pages/GamesNearPage/GamesNearPage.tsx
  src/pages/GamesParticipatePage/GamesParticipatePage.tsx
Labels: 기능, D-0

#128 All-services(전체 메뉴) 페이지 이동 추가
  src/consts/pathName.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/ProfilePage/Profile.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/routes/router.tsx
Labels: 긴급, D-0

#132 Calendar 컴포넌트 스타일 수정
  src/components/Calendar/Calendar.styles.ts
  src/components/Calendar/Calendar.tsx
  src/pages/CreateGamePage/CreateGamePage.tsx
Labels: 스타일링

#133 리뷰하기 모달 구현 및 기타 버그 수정
  src/pages/CreatePage/CreatePage.tsx
  src/pages/CreatePage/CreatePageCard.tsx
  src/pages/ProfilePage/Profile.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/ReviewPage/ReviewPage.tsx
Labels: 긴급, 기능, 버그, 리팩터링

#140 Crew api 타입 정의
  src/type/api/crews.ts
Labels: 기능, D-0

#142 게스트 매치 관련 공통로직 유틸 함수로 분리 및 리팩토링
  src/components/MatchItem/MatchItem.tsx
  src/pages/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/pages/GamesHostPage/GamesHostPage.tsx
  src/pages/GamesParticipatePage/GamesParticipatePage.tsx
  src/utils/domain.ts
Labels: 기능, 리팩터링

#145 크루 아이템 컴포넌트 구현
  src/assets/default.svg
  src/components/CrewItem/CrewItem.styles.ts
  src/components/CrewItem/CrewItem.tsx
  src/components/CrewItem/index.ts
Labels: 기능

#147 리뷰페이지 구현
  src/hooks/mutations/useMannerScoreReviewPatchMutation.ts
  src/mocks/handlers/game.ts
  src/pages/MannerScoreReviewPage/MannerScoreReviewPage.style.ts
  src/pages/MannerScoreReviewPage/MannerScoreReviewPage.tsx
  src/pages/MannerScoreReviewPage/ToggleButton.style.ts
  src/pages/MannerScoreReviewPage/ToggleButton.tsx
  src/pages/MannerScoreReviewPage/index.ts
  src/pages/ReviewPage/ToggleButtons.hook.ts
  src/pages/ReviewPage/index.ts
  src/routes/router.tsx
  src/type/api/games.ts
Labels: 기능, 리팩터링, D-2

#152 크루 생성 페이지 구현
  src/api/crews/postCrew.ts
  src/hooks/mutations/usePostMutation.ts
  src/pages/CreateCrewPage/CreateCrewPage.styles.ts
  src/pages/CreateCrewPage/CreateCrewPage.tsx
  src/pages/CreateCrewPage/index.ts
  src/routes/router.tsx
  src/styles/button.ts
Labels: 기능

#144 로그인 kakao oauth
  src/api/member/getAuthRedirect.ts
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/components/shared/ToggleButton/ToggleButtons.hook.ts
  src/consts/positions.ts
  src/hooks/mutations/useRegistrationMutation.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/RedirectPage/RedirectPage.tsx
  src/pages/RedirectPage/index.ts
  src/pages/RegisterPage/RegisterPage.tsx
  src/routes/router.tsx
Labels: 기능

#158 axiosInstance baseUrl 변경
  src/api/axiosInstance.ts
  src/api/games/patchGameParticipate.ts
  src/api/games/patchMannerScoreReview.ts
  src/api/games/postGame.ts
  src/api/games/postGameParticipate.ts
  src/api/member/postRegistration.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/GamesHostPage/GamesHostPage.tsx
  src/utils/formatDate.ts
  vite.config.ts
  vitest.config.ts
Labels: 기능

#157 크루 참여 승인 페이지 구현
  src/api/crews/deleteCrewParticipate.ts
  src/api/crews/getCrewMembers.ts
  src/api/crews/patchCrewParticipate.ts
  src/components/Participation/Participation.style.ts
  src/components/Participation/Participation.tsx
  src/components/Participation/components/AllowCard/AllowCard.style.ts
  src/components/Participation/components/AllowCard/AllowCard.tsx
  src/components/Participation/components/AllowCard/index.ts
  src/components/Participation/index.ts
  src/hooks/mutations/useAllowCrewParticipateMutation.ts
  src/hooks/mutations/useDisallowCrewParticipateMutation.ts
  src/hooks/queries/useCrewMembersQuery.ts
  src/pages/CrewsManageParticipatePage/CrewsManageParticipatePage.tsx
  src/pages/CrewsManageParticipatePage/index.ts
  src/pages/GamesManagePage/index.ts
  src/pages/GamesManageParticipatePage/GamesManageParticipatePage.tsx
  src/pages/GamesManageParticipatePage/index.ts
  src/routes/router.tsx
Labels: 기능

#160 추천 크루 목록 페이지 구현
  package-lock.json
  package.json
  src/api/crews/getNearCrewList.ts
  src/hooks/queries/useNearCrewListQuery.ts
  src/mocks/data/crew.ts
  src/mocks/handlers/crew.ts
  src/pages/CrewsRecommendPage/CrewsRecommendPage.styles.ts
  src/pages/CrewsRecommendPage/CrewsRecommendPage.tsx
  src/pages/CrewsRecommendPage/index.ts
  src/routes/router.tsx
  src/stores/accessToken.store.ts
  src/stores/loginInfo.store.ts
  src/type/api/crews.ts
Labels: 기능

#162 useGamesQuery 선택옵션값 필수로 변경
  src/consts/location.ts
  src/consts/network.ts
  src/hooks/queries/useGamesQuery.ts
  src/pages/GamesNearPage/GamesNearPage.tsx
Labels: 긴급, 버그

#163 내가 속한 크루 목록 페이지 구현
  src/api/member/getJoinedCrews.ts
  src/hooks/queries/useJoinedCrewsQuery.ts
  src/mocks/handlers/member.ts
  src/pages/CrewsParticipatePage/CrewsParticipatePage.styles.ts
  src/pages/CrewsParticipatePage/CrewsParticipatePage.tsx
  src/pages/CrewsParticipatePage/index.ts
  src/routes/router.tsx
Labels: 기능

#164 내가 만든 크루 페이지 구현
  src/api/member/getCreatedCrews.ts
  src/hooks/queries/useCreatedCrewsQuery.ts
  src/pages/CrewsChiefPage/CrewsChiefPage.style.ts
  src/pages/CrewsChiefPage/CrewsChiefPage.tsx
  src/pages/CrewsChiefPage/index.ts
  src/routes/router.tsx
  src/type/api/member.ts
Labels: 기능, D-2

#165 크루 상세 페이지 구현
  src/api/crews/getCrewDetail.ts
  src/api/crews/postCrewParticipate.ts
  src/components/shared/Text/Text.styles.ts
  src/components/shared/Text/Text.tsx
  src/hooks/mutations/useCrewParticipateCreateMutation.ts
  src/hooks/queries/useCrewDetailQuery.ts
  src/mocks/data/crew.ts
  src/mocks/handlers/crew.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.styles.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
  src/pages/CrewsDetailPage/index.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/routes/router.tsx
  src/type/api/crews.ts
Labels: 기능

#167 게스트 모집글 생성 페이지 api 수정
  src/mocks/handlers/game.ts
  src/pages/CreateGamePage/CreateGamePage.tsx
  src/type/api/games.ts
Labels: 기능

#169 메인페이지 추천 크루 ui 및 api 구현
  src/mocks/data/crew/nearCrewList.ts
  src/mocks/handlers/crew/nearCrewList.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/useMainPageNearCrewListQuery.ts
Labels: 기능, D-2

#171 크루 만들기 페이지 api 수정
  src/api/crews/postCrew.ts
  src/hooks/mutations/useCrewMutation.ts
  src/mocks/data/crew.ts
  src/mocks/handlers/crew.ts
  src/pages/CreateCrewPage/CreateCrewPage.tsx
  src/type/api/crews.ts
Labels: 기능

#176 크루 만들기 페이지 리팩토링
  src/components/ConditionalFormInput/ConditionalFormInput.styles.ts
  src/components/ConditionalFormInput/ConditionalFormInput.tsx
  src/components/ConditionalFormInput/index.ts
  src/consts/createCrewOptions.ts
  src/pages/CreateCrewPage/CreateCrewPage.styles.ts
  src/pages/CreateCrewPage/CreateCrewPage.tsx
  src/pages/CreateGamePage/CreateGamePage.tsx
Labels: 기능, 리팩터링

#177 프로필 페이지 수정
  src/assets/handHeart.svg
  src/assets/heart.svg
  src/consts/pathName.ts
  src/pages/ProfilePage/Profile.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/routes/router.tsx
Labels: 기능, 리팩터링, 스타일링

#179 내가 참여한 게스트 매치 api 수정
  src/api/member/getConfirmedGames.ts
Labels: 긴급

#181 게스트 모집 참여 신청 api 수정
  src/api/games/postGameParticipate.ts
  src/mocks/handlers/game.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/type/api/games.ts
Labels: 긴급

#183 루트 Error Boundary 추가
  package-lock.json
  package.json
  src/pages/ErrorPage/ErrorPage.styles.ts
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/ErrorPage/index.ts
  src/routes/router.tsx
  src/type/FallbackProps.ts
Labels: 기능

#197 ErrorPage 에 헤더, 하단Nav바 추가 및 FallbackPage구현
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Navbar/Navbar.tsx
  src/hooks/useHeaderTitle.ts
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/FallbackPage/FallbackPage.styles.ts
  src/pages/FallbackPage/FallbackPage.tsx
  src/pages/FallbackPage/index.ts
  src/pages/Layout.tsx
  src/routes/router.tsx
Labels: 기능

#204 알림 아이템 컴포넌트 구현
  src/components/NotificationItem/NotificationItem.styles.ts
  src/components/NotificationItem/NotificationItem.tsx
  src/components/NotificationItem/components/NotificationItemImage/NotificationItemImage.tsx
  src/components/NotificationItem/components/NotificationItemImage/index.ts
  src/components/NotificationItem/components/NotificationItemMatchStatus/NotificationItemMatchStatus.styles.ts
  src/components/NotificationItem/components/NotificationItemMatchStatus/NotificationItemMatchStatus.tsx
  src/components/NotificationItem/components/NotificationItemMatchStatus/index.ts
  src/components/NotificationItem/index.ts
  src/components/shared/Text/Text.styles.ts
  src/components/shared/Text/Text.tsx
  src/utils/createdAtToString.ts
Labels: 기능

#206 resetErrorBoundary 로직 버그 수정
  src/components/Header/Header.tsx
  src/components/Navbar/Navbar.tsx
  src/hooks/usePathnameChange.ts
  src/pages/ErrorPage/ErrorPage.tsx
Labels: 긴급, 버그, D-0

#210 fix: 알림페이지 router 수정
  src/routes/router.tsx
Labels: 긴급

#212 알림 페이지 스크롤 생기는 버그 수정
  src/pages/NotificationPage/NotificationPage.styles.ts
  src/pages/NotificationPage/NotificationPage.tsx
Labels: 긴급, 버그

#195 Calendar 컴포넌트 스타일 수정
  src/components/Calendar/Calendar.styles.ts
  src/components/Calendar/Calendar.tsx
Labels: 스타일링

#201 useMainPageNearGamesQuery 수정
  src/pages/MainPage/useMainPageNearGamesQuery.ts
Labels: 긴급, 버그

#189 헤더 프로필 버튼 클릭 핸들러 변경, 헤더 프로필 이미지 변경
  src/components/Header/Header.tsx
Labels: 긴급, 리팩터링

#199 크루 상세 페이지 크루 관리 버튼 수정
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
Labels: 긴급, 버그

#198 크루 상세 페이지 ui 수정
  src/pages/CrewsDetailPage/CrewsDetailPage.styles.ts
Labels: 긴급, 버그

#196 회원가입, 로그인 수정
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/RedirectPage/RedirectPage.tsx
  src/pages/RegisterPage/RegisterPage.tsx
Labels: 기능

#214 EventSource 에 연결하는 훅 구현
  package-lock.json
  package.json
  src/api/axiosInstance.ts
  src/consts/network.ts
  src/hooks/useEventSource.ts
  src/pages/NotificationPage/NotificationPage.tsx
Labels: 기능

#227 회원가입 버그 수정
  src/pages/RedirectPage/RedirectPage.tsx
Labels: 긴급, 버그

#228 랭킹 페이지 모달 컨텐츠 UI 구현
  src/components/InfoItem/InfoItem.tsx
  src/components/InfoItem/InfoItems.styles.ts
  src/components/InfoItem/index.ts
  src/components/Modal/Modal.tsx
  src/components/RankingModalContent/RankingModalContent.styles.ts
  src/components/RankingModalContent/RankingModalContent.tsx
  src/components/RankingModalContent/index.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
Labels: 기능

#226 랭킹 페이지 UI 구현
  src/components/shared/Text/Text.styles.ts
  src/components/shared/Text/Text.tsx
  src/consts/pathName.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/CrewsRankingPage/CrewsRankingPage.styles.ts
  src/pages/CrewsRankingPage/CrewsRankingPage.tsx
  src/pages/CrewsRankingPage/components/RankingItem/RankingItem.styles.ts
  src/pages/CrewsRankingPage/components/RankingItem/RankingItem.tsx
  src/pages/CrewsRankingPage/components/RankingItem/getRankingItemBackgroundColor.ts
  src/pages/CrewsRankingPage/components/RankingItem/index.ts
  src/pages/CrewsRankingPage/index.ts
  src/routes/router.tsx
Labels: 기능

#215 메세지 페이지 ui 구현
  src/components/shared/Input/Input.style.ts
  src/components/shared/Input/Input.tsx
  src/pages/Layout.tsx
  src/pages/MessageRoomPage/Message.tsx
  src/pages/MessageRoomPage/MessageRoomPage.style.ts
  src/pages/MessageRoomPage/MessageRoomPage.tsx
  src/pages/MessageRoomPage/index.ts
  src/routes/router.tsx
Labels: 기능

#219 메세지 목록 페이지 ui 구현
  src/pages/MessageListPage/MessageItem.tsx
  src/pages/MessageListPage/MessageListPage.style.ts
  src/pages/MessageListPage/MessageListPage.tsx
  src/pages/MessageListPage/index.ts
  src/routes/router.tsx
Labels: 기능

#242 채팅 관련 type, api, tanstack query hook 작성
  src/api/chat/getAllChatMessages.ts
  src/api/chat/getAllChatRoomList.ts
  src/api/chat/getChatRoomDetails.ts
  src/api/chat/getPersonalChatRoomExisted.ts
  src/api/chat/postCreatePersonalChatRoom.ts
  src/hooks/mutations/useCreatePersonalChatRoomMutation.ts
  src/hooks/queries/useAllChatMessagesQuery.ts
  src/hooks/queries/useAllChatRoomListQuery.ts
  src/hooks/queries/useChatRoomDetails.ts
  src/hooks/queries/usePersonalChatRoomExistedQuery.ts
  src/type/api/chat.ts
  src/type/models/ChatMember.ts
  src/type/models/ChatMessage.ts
  src/type/models/ChatRoom.ts
Labels: 기능

#192 리뷰페이지 버그 수정
  src/pages/MannerScoreReviewPage/MannerScoreReviewPage.tsx
Labels: 버그, D-2

#221 NotFoundPage 구현
  src/pages/NotFoundPage/NotFoundPage.styles.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/NotFoundPage/index.ts
  src/routes/router.tsx
Labels: 기능

#230 infinite query 버그 수정
  src/hooks/queries/useGamesQuery.ts
  src/hooks/queries/useNearCrewListQuery.ts
Labels: 긴급, 버그, D-0

#232 모바일 사파리 로그인 버튼 깨지는 문제 수정
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
Labels: 긴급, 버그, D-0

#236 랭킹 페이지에 랭킹 모달 붙이기
  src/assets/tooltip.svg
  src/components/Modal/Modal.styles.ts
  src/components/Modal/Modal.tsx
  src/components/RankingModalContent/RankingModalContent.tsx
  src/pages/CrewsRankingPage/CrewsRankingPage.tsx
Labels: 기능

#240 메인 페이지 경기 시간 렌더링 버그 및 자잘한 버그 수정
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/CreatePage/CreatePage.style.ts
  src/pages/CrewsChiefPage/CrewsChiefPage.tsx
  src/pages/CrewsRecommendPage/CrewsRecommendPage.styles.ts
  src/pages/ErrorPage/ErrorPage.styles.ts
  src/pages/FallbackPage/FallbackPage.styles.ts
  src/pages/GamesNearPage/GamesNearPage.styles.ts
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MannerScoreReviewPage/MannerScoreReviewPage.style.ts
Labels: 버그, D-2

#243 게스트 모집글 작성 페이지 리팩터링
  src/components/ConditionalFormInput/ConditionalFormInput.tsx
  src/pages/CreateGamePage/CreateGamePage.tsx
  src/pages/CreateGamePage/consts/createGameOptions.ts
  src/pages/CreateGamePage/useCreateGamePage.ts
Labels: 리팩터링

#245 크루 생성 페이지 리팩터링
  package-lock.json
  package.json
  src/App.tsx
  src/consts/createCrewOptions.ts
  src/consts/location.ts
  src/pages/CreateCrewPage/CreateCrewPage.styles.ts
  src/pages/CreateCrewPage/CreateCrewPage.tsx
  src/pages/CreateCrewPage/consts/createCrewOptions.ts
  src/pages/CreateCrewPage/useCreateCrewPage.ts
  src/styles/styles.ts
Labels: 리팩터링

#247 Skeleton 컴포넌트 구현
  src/components/Skeleton/Skeleton.tsx
  src/components/Skeleton/SkeletonContext.ts
  src/components/Skeleton/SkeletonItem/SkeletonItem.styles.ts
  src/components/Skeleton/SkeletonItem/SkeletonItem.tsx
  src/components/Skeleton/SkeletonItem/generateSkeletonKeyframes.ts
  src/components/Skeleton/SkeletonItem/index.ts
  src/components/Skeleton/index.ts
  src/components/Skeleton/useSkeletonContext.ts
  src/components/shared/Flex/Flex.ts
Labels: 기능

#249 지도 페이지 구현
  index.html
  package-lock.json
  package.json
  src/api/map/getGamesByAddress.ts
  src/api/map/getGamesInMap.ts
  src/assets/mapCurrentLocation.svg
  src/assets/mapMarker.svg
  src/assets/myLocation.svg
  src/assets/refresh.svg
  src/mocks/handlers/game.ts
  src/pages/MapPage/CurrentLocationMarker.tsx
  src/pages/MapPage/GameMarkers.tsx
  src/pages/MapPage/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/MapPage/GamesDetailPage/GamesDetailPage.tsx
  src/pages/MapPage/GamesDetailPage/index.ts
  src/pages/MapPage/GamesNearInMap.tsx
  src/pages/MapPage/MapPage.style.ts
  src/pages/MapPage/MapPage.tsx
  src/pages/MapPage/MatchItem/MatchItem.styles.ts
  src/pages/MapPage/MatchItem/MatchItem.tsx
  src/pages/MapPage/MatchItem/components/BottomButton/BottomButton.styles.ts
  src/pages/MapPage/MatchItem/components/BottomButton/BottomButton.tsx
  src/pages/MapPage/MatchItem/components/BottomButton/index.ts
  src/pages/MapPage/MatchItem/index.ts
  src/pages/MapPage/index.ts
  src/pages/MapPage/useMapPage.ts
  src/routes/router.tsx
  src/type/models/Game.ts
  tsconfig.json
Labels: 기능, 스타일링, D-2

#251 queryClient defaultOption 변경
  src/App.tsx
Labels: 기능

#254 채팅 페이지 api 연동
  index.html
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/consts/chatRoomTabTitle.ts
  src/pages/ChattingPage/Chat.tsx
  src/pages/ChattingPage/ChatTitle.tsx
  src/pages/ChattingPage/ChattingPage.style.ts
  src/pages/ChattingPage/ChattingPage.tsx
  src/pages/ChattingPage/getTitlePagePath.service.ts
  src/pages/ChattingPage/index.ts
  src/pages/ChattingPage/stompApi.ts
  src/pages/ChattingPage/useChattingPage.ts
  src/pages/MessageRoomPage/Message.tsx
  src/pages/MessageRoomPage/MessageRoomPage.tsx
  src/pages/MessageRoomPage/index.ts
  src/routes/router.tsx
Labels: 기능

#258 채팅 목록 페이지 api 연동
  src/pages/ChatRoomListPage/ChatRoomItem.tsx
  src/pages/ChatRoomListPage/ChatRoomListPage.style.ts
  src/pages/ChatRoomListPage/ChatRoomListPage.tsx
  src/pages/ChatRoomListPage/index.ts
  src/pages/ChatRoomListPage/useChatRoomListPage.ts
  src/pages/MessageListPage/MessageItem.tsx
  src/pages/MessageListPage/MessageListPage.tsx
  src/pages/MessageListPage/index.ts
  src/pages/ProfilePage/Profile.tsx
  src/routes/router.tsx
  src/stores/chatRoomTab.store.ts
  src/utils/getTimeStamp.ts
Labels: 기능

#259 크루 랭킹 api 구현 및 연결
  src/api/ranking/getCrewsRanking.ts
  src/components/InfoItem/InfoItem.tsx
  src/components/InfoItem/InfoItems.styles.ts
  src/components/RankingModalContent/RankingModalContent.tsx
  src/hooks/queries/useCrewsRankingQuery.ts
  src/mocks/data/ranking.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/ranking.ts
  src/pages/CrewsRankingPage/CrewsRankingPage.tsx
  src/type/models/CrewRank.ts
  src/type/models/Ranking.ts
Labels: 기능

#260 Hotfix/merge conflict
  package-lock.json
  src/components/Navbar/Navbar.tsx
  src/consts/pathName.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/ChatRoomListPage/ChatRoomListPage.tsx
  src/pages/ChattingPage/useChattingPage.ts
  src/pages/Layout.tsx
  src/pages/ProfilePage/Profile.tsx
  src/routes/router.tsx
Labels: 긴급

#266 지도 페이지 svg 파일명 변경
  src/pages/MapPage/MapPage.tsx
Labels: 긴급, 버그

#269 지도페이지 모달이 닫힌 후에 다른페이지로 이동해야하는 이슈 발생
  src/pages/MapPage/GamesDetailPage/GamesDetailPage.tsx
  src/pages/MapPage/MapPage.tsx
Labels: 긴급, 버그

#270 fix: svg src에서 import 해서 쓰는 걸로 변경
  src/pages/MapPage/CurrentLocationMarker.tsx
  src/pages/MapPage/GameMarkers.tsx
  src/pages/MapPage/MapPage.tsx
Labels: 긴급, 버그

#271 채팅 ui 버그 수정
  src/pages/ChatRoomListPage/ChatRoomItem.tsx
  src/pages/ChatRoomListPage/ChatRoomListPage.style.ts
  src/pages/ChatRoomListPage/ChatRoomListPage.tsx
  src/pages/ChattingPage/ChattingPage.style.ts
Labels: 긴급, 버그

#276 accessToken refresh 하는 axios interceptor 구현
  src/api/axiosInstance.ts
  src/api/interceptors.ts
Labels: 기능

#278 handleAuthError interceptor 오류 수정
  src/api/interceptors.ts
Labels: 긴급, 버그

#280 포지션목록, 지역목록 api 함수, 모델타입, query hook 구현 & 연동
  src/api/data/getLocations.ts
  src/api/data/getPositions.ts
  src/hooks/queries/useLocationsQuery.ts
  src/hooks/queries/usePositionsQuery.ts
  src/pages/CreateCrewPage/CreateCrewPage.tsx
  src/pages/CreateCrewPage/useCreateCrewPage.ts
  src/pages/RegisterPage/RegisterPage.tsx
  src/type/models/Location.ts
  src/type/models/Position.ts
Labels: 기능, 리팩터링

#274 로그인한 사용자가 위치정보동의 거부했을 경우의 로직 수정
  src/pages/MapPage/useMapPage.ts
Labels: 버그, D-0

#283 docs: README 수정
  README.md
Labels: 기능

#286 스켈레톤 페이지 구현
  src/components/SkeletonCardList/SkeletonCardList.tsx
  src/hooks/queries/useJoinedCrewsQuery.ts
  src/hooks/useHeaderTitle.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.loading.tsx
  src/pages/CrewsDetailPage/CrewsDetailPage.styles.ts
  src/pages/CrewsDetailPage/index.ts
  src/pages/CrewsRecommendPage/CrewsRecommendPage.tsx
  src/pages/GamesDetailPage/GamesDetailPage.loading.tsx
  src/pages/GamesDetailPage/index.ts
  src/pages/GamesNearPage/GamesNearPage.loading.tsx
  src/pages/GamesNearPage/GamesNearPage.tsx
  src/pages/GamesNearPage/index.ts
  src/pages/MainPage/MainPage.loading.tsx
  src/pages/MainPage/index.ts
  src/pages/__components__/CardListPageSkeleton/CardListPageSkeleton.styles.ts
  src/pages/__components__/CardListPageSkeleton/CardListPageSkeleton.tsx
  src/pages/__components__/CardListPageSkeleton/index.ts
  src/pages/__components__/ManagePageSkeleton/ManagePageSkeleton.tsx
  src/pages/__components__/ManagePageSkeleton/index.ts
  src/routes/router.tsx
Labels: 기능

#291 Update dispatch_to_1eecan.yml
  .github/workflows/dispatch_to_1eecan.yml
Labels: 긴급

#284 chat api 변경 내역 반영 및 비로그인 시 프로필 페이지 접근 불가 버그 수정
  src/hooks/useChatOnButtonClick.ts
  src/pages/ChatRoomListPage/ChatRoomListPage.style.ts
  src/pages/ChatRoomListPage/useChatRoomListPage.ts
  src/pages/ChattingPage/stompApi.ts
  src/pages/ProfilePage/Profile.tsx
  src/type/api/chat.ts
Labels: 긴급, 버그

#304 Refactor/#300 auto deployment
  .github/workflows/dispatch.yml
  .github/workflows/trigger_dispatch.yml
Labels: 기타

#295 UTC 타임 변환 함수 작성 및 채팅 페이지에 적용
  src/pages/ChatRoomListPage/ChatRoomItem.tsx
  src/pages/ChattingPage/Chat.tsx
  src/type/models/ChatMessage.ts
  src/type/models/ChatRoom.ts
  src/utils/convertUTCToKoreanTime.ts
  src/utils/getTimeStamp.ts
Labels: 기능, 버그

#314 지도 페이지 qa 피드백 적용
  src/pages/MapPage/MapPage.tsx
  src/pages/MapPage/useMapPage.ts
Labels: 버그, 리팩터링, D-1

#296 로그아웃 구현(api 호출 및 refreshToken 만료 에러처리)
  src/api/interceptors.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/AuthErrorPage/AuthErrorPage.styles.ts
  src/pages/AuthErrorPage/AuthErrorPage.tsx
  src/pages/AuthErrorPage/index.ts
  src/routes/router.tsx
  src/utils/isValidServerError.ts
Labels: 기능

#306 크루 생성 페이지 UI 수정
  src/pages/CreateCrewPage/CreateCrewPage.styles.ts
  src/pages/CreateCrewPage/CreateCrewPage.tsx
Labels: 스타일링

#308 프로필 페이지 내 포지션, 크루 클릭 이벤트 구현
  src/pages/ProfilePage/Profile.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
Labels: 기능

#310 게스트 모집 상세 페이지 대화하기 버튼 훅 적용
  src/pages/GamesDetailPage/GamesDetailPage.tsx
Labels: 기능

#315 채팅 메세지 내역이 캐시되어 업데이트 되지 않는 버그 수정
  src/hooks/queries/useAllChatMessagesQuery.ts
Labels: 긴급, 버그

#317 채팅 목록 페이지 쿼리 수정
  src/hooks/queries/useAllChatRoomListQuery.ts
  src/pages/ChatRoomListPage/ChatRoomListPage.tsx
  src/pages/ChatRoomListPage/useChatRoomListPage.ts
Labels: 기능, 버그, 리팩터링

#319 내가 만든 크루 페이지에서 크루 상세 페이지로 이동할 수 있는 기능
  src/assets/dots.svg
  src/pages/CrewsChiefPage/CrewCheifModal.tsx
  src/pages/CrewsChiefPage/CrewsChiefPage.style.ts
  src/pages/CrewsChiefPage/CrewsChiefPage.tsx
  src/pages/CrewsChiefPage/useCrewChiefModal.ts
Labels: 기능

#321 페이지 이동 시 스크롤이 내려가 있는 버그
  src/routes/ScrollTop.tsx
  src/routes/router.tsx
Labels: 긴급, 버그, D-0

#322 게스트 모집글, 크루 생성 페이지 qa 피드백 반영
  src/components/ConditionalFormInput/ConditionalFormInput.styles.ts
  src/components/TextArea/TextArea.tsx
  src/components/shared/ToggleButton/ToggleButtons.hook.ts
  src/pages/CreateCrewPage/CreateCrewPage.styles.ts
  src/pages/CreateCrewPage/useCreateCrewPage.ts
  src/pages/CreateGamePage/CreateGamePage.styles.ts
  src/pages/CreateGamePage/CreateGamePage.tsx
  src/pages/CreateGamePage/consts/createGameOptions.ts
  src/pages/CreateGamePage/useCreateGamePage.ts
Labels: 기능, 버그, 스타일링

#324 크루 상세 페이지에서 크루장 정보가 표시되는 기능 추가
  src/assets/crown.svg
  src/pages/CrewsDetailPage/CrewsDetailPage.styles.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
Labels: 기능

#326 크루장 표시 렌더링 로직 수정
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
Labels: 긴급, 버그, D-0

#336 채팅 qa 반영
  src/api/chat/getPersonalChatRoomExisted.ts
  src/hooks/useChatOnButtonClick.ts
  src/pages/ChatRoomListPage/ChatRoomList.tsx
  src/pages/ChatRoomListPage/ChatRoomListPage.tsx
  src/pages/ChatRoomListPage/SkeletonChatRoomList.tsx
  src/pages/ChatRoomListPage/useChatRoomList.ts
  src/pages/ChattingPage/quitChatCondition.ts
  src/pages/ChattingPage/useChattingPage.ts
  src/type/api/chat.ts
Labels: 긴급, 기능, 버그

#312 크루 가입 신청여부, 게스트 모집 참여 신청여부 관련 api 및 ui 작업
  src/api/member/getCrewRegistrationStatus.ts
  src/api/member/getGameRegistrationStatus.ts
  src/hooks/mutations/useCrewParticipateCreateMutation.ts
  src/hooks/mutations/useGameParticipateCreateMutation.ts
  src/hooks/queries/useCrewRegistrationStatusQuery.ts
  src/hooks/queries/useGameRegistrationStatusQuery.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
  src/pages/CrewsDetailPage/ParticipateButton.tsx
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/pages/GamesDetailPage/ParticipateButton.tsx
  src/type/api/member.ts
Labels: 기능

#330 크루, 게임 상세 페이지 로그인 유도 버튼 추가(로그인 후 참여 신청하기)
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
  src/pages/GamesDetailPage/GamesDetailPage.tsx
Labels: 기능

#332 메인 페이지 '내 근처의 경기' 문구 수정
  src/pages/MainPage/MainPage.loading.tsx
  src/pages/MainPage/MainPage.tsx
Labels: 기능

#333 게스트 모집글에 선호 포지션 정보 추가 + 참가비 콤마로 구분
  src/pages/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
Labels: 기능

#335 매치관리 & 크루관리 페이지 참여 요청 없을 때 UI 처리
  src/components/Participation/Participation.style.ts
  src/components/Participation/Participation.tsx
  src/components/Participation/components/AllowCard/AllowCard.tsx
Labels: 기능

#337 로그인 필요한 페이지들 리디렉션 기능 추가
  src/pages/AllServicesPage/AllServicesPage.style.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/AllServicesPage/MenuItem.tsx
  src/pages/ChatRoomListPage/useChatRoomList.ts
  src/pages/CreateCrewPage/useCreateCrewPage.ts
  src/pages/CreateGamePage/useCreateGamePage.ts
  src/pages/CrewsChiefPage/CrewsChiefPage.tsx
  src/pages/CrewsParticipatePage/CrewsParticipatePage.tsx
  src/pages/GamesHostPage/GamesHostPage.tsx
  src/pages/GamesParticipatePage/GamesParticipatePage.tsx
  src/pages/NotificationPage/NotificationPage.tsx
  src/routes/LoginRequireBoundary.tsx
  src/routes/lazyPage.ts
  src/routes/router.tsx
Labels: 기능

#339 virtualscroll 컴포넌트 hook 분리
  src/components/ConditionalInput/ConditionalInput.styles.ts
  src/components/ConditionalInput/ConditionalInput.tsx
  src/components/ConditionalInput/index.ts
  src/components/shared/VirtualScroll/VirtualScroll.hook.ts
  src/components/shared/VirtualScroll/VirtualScroll.tsx
  src/consts/location.ts
  src/consts/positions.ts
Labels: 리팩터링

#341 대화하기 훅 수정 및 디버그 메세지 삭제
  src/consts/chat.ts
  src/consts/chatRoomTabTitle.ts
  src/hooks/useChatOnButtonClick.ts
  src/pages/AllServicesPage/AllServicesPage.tsx
  src/pages/ChatRoomListPage/ChatRoomItem.tsx
  src/pages/ChatRoomListPage/ChatRoomListPage.style.ts
  src/pages/ChatRoomListPage/ChatRoomListPage.tsx
  src/pages/ChattingPage/Chat.tsx
  src/pages/ChattingPage/ChattingPage.style.ts
  src/pages/ChattingPage/getTitlePagePath.service.ts
  src/pages/ChattingPage/quitChatCondition.ts
  src/pages/ChattingPage/stompApi.ts
  src/pages/ChattingPage/useChattingPage.ts
  src/stores/chatRoomTab.store.ts
Labels: 기능, 버그, 기타

#346 페이지 컴포넌트들 코드스플리팅 적용
  src/routes/lazyPage.ts
  src/routes/router.tsx
Labels: 기능

#351 코드 스플리팅 오류 수정
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/routes/lazyPage.ts
  src/routes/lazyPages.ts
  src/routes/router.tsx
Labels: 긴급, 버그, D-0

#237 알림 key값에 따라 NotificationItem 컴포넌트 구체화
  src/App.tsx
  src/api/alarms/deleteAlarms.ts
  src/api/alarms/getAlarms.ts
  src/api/alarms/getAlarmsUnread.ts
  src/api/alarms/patchCrewAlarms.ts
  src/api/alarms/patchGameAlarms.ts
  src/components/Header/Badge.tsx
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/components/NotificationItem/NotificationItem.tsx
  src/components/NotificationItem/components/NotificationItemMatchStatus/NotificationItemMatchStatus.styles.ts
  src/hooks/mutations/useAlarmsDeleteMutation.ts
  src/hooks/mutations/useCrewAlarmsPatchMutation.ts
  src/hooks/mutations/useGameAlarmsPatchMutation.ts
  src/hooks/queries/useAlarmsQuery.ts
  src/hooks/queries/useAlarmsUnreadQuery.ts
  src/hooks/useEventSource.ts
  src/pages/NotificationPage/NotificationPage.tsx
  src/pages/NotificationPage/components/CrewNotificationItem/CrewNotificationItem.tsx
  src/pages/NotificationPage/components/CrewNotificationItem/index.ts
  src/pages/NotificationPage/components/GameNotificationItem/GameNotificationItem.tsx
  src/pages/NotificationPage/components/GameNotificationItem/getGameNotificationTitle.ts
  src/pages/NotificationPage/components/GameNotificationItem/index.ts
  src/type/api/alarm.ts
  src/type/models/Alarm.ts
  src/type/models/index.ts
Labels: 기능

#354 EventSource subscribe url 수정
  src/App.tsx
Labels: 긴급, 버그, D-0

#359 카카오 맵 api parse blocking 경고 해결 및 global define 변경
  index.html
  vite.config.ts
Labels: 기타

#356 아이폰 사파리 regExp 오류 수정
  src/pages/GamesDetailPage/GamesDetailPage.tsx
Labels: 긴급, 버그, D-0

#361 크루 아이템, 매치 아이템 ui 깨지는 버그
  src/components/CrewItem/CrewItem.styles.ts
  src/components/MatchItem/MatchItem.styles.ts
  src/components/MatchItem/MatchItem.tsx
  src/pages/ChatRoomListPage/ChatRoomListPage.style.ts
Labels: 긴급, 버그

#367 게스트 매치 상세 페이지 지도로 보기 구현
  src/pages/GamesDetailPage/GameLocation.tsx
  src/pages/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
Labels: 기능

#369 알림 배지에 Suspense, ErrorBoundary 래핑
  src/api/axiosInstance.ts
  src/components/Header/Header.tsx
Labels: 기능

#381 크루 랭킹 페에지, 알림 페이지 스켈레톤 UI 추가
  src/pages/__components__/ItemListPageSkeleton/ItemListPageSkeleton.styles.ts
  src/pages/__components__/ItemListPageSkeleton/ItemListPageSkeleton.tsx
  src/pages/__components__/ItemListPageSkeleton/index.ts
  src/routes/router.tsx
Labels: 기능

#375 알림 PATCH 요청 관련 버그 수정
  src/api/alarms/patchCrewAlarms.ts
  src/api/alarms/patchGameAlarms.ts
  src/hooks/mutations/useCrewAlarmsPatchMutation.ts
  src/hooks/mutations/useGameAlarmsPatchMutation.ts
  src/pages/NotificationPage/NotificationPage.tsx
Labels: 긴급, 버그

#377 크루 랭킹 페이지 모달 안뜨면서 렌더링 오류나는 버그
  src/pages/CrewsRankingPage/CrewsRankingPage.tsx
  src/type/models/CrewRank.ts
Labels: 긴급, 버그

#380 비동기 요청 안하는 페이지들 코드 스플리팅 적용 안하기
  src/routes/lazyPages.ts
  src/routes/router.tsx
Labels: 리팩터링

#394 알림 목록 페이지 무한 스크롤 구현
  src/components/NotificationItem/components/NotificationItemImage/NotificationItemImage.tsx
  src/pages/NotificationPage/NotificationPage.tsx
  src/pages/NotificationPage/components/CrewNotificationItem/CrewNotificationItem.tsx
  src/type/models/Alarm.ts
Labels: 기능

#392 게스트 모집글 생성 페이지 상세설명 기본값 삭제
  src/pages/CreateGamePage/CreateGamePage.tsx
Labels: 기타

#384 게스트/크루 참여 수락/거절 시 토스트 구현
  src/hooks/mutations/useAllowCrewParticipateMutation.ts
  src/hooks/mutations/useAllowGameParticipateMutation.ts
  src/hooks/mutations/useDisallowCrewParticipateMutation.ts
  src/hooks/mutations/useDisallowGameParticipateMutation.ts
Labels: 기능

#386 지도 페이지 게스트 매치가 없는 경우에 대한 처리
  src/pages/MapPage/GamesNearInMap.tsx
Labels: 버그

#389 크루 랭킹 모달 ui 깨짐 버그
  src/components/RankingModalContent/RankingModalContent.styles.ts
  src/components/RankingModalContent/RankingModalContent.tsx
  src/pages/CrewsRankingPage/components/RankingItem/RankingItem.styles.ts
  src/pages/CrewsRankingPage/components/RankingItem/RankingItem.tsx
Labels: 긴급, 버그

#366 로그인 페이지 ui 변경
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
Labels: 기능

#397 모달 닫힐 때 ui 깨지는 버그
  src/pages/CrewsRankingPage/CrewsRankingPage.tsx
Labels: 긴급, 버그, D-0

#399 에러 페이지 문구 수정
  src/pages/ErrorPage/ErrorPage.tsx
Labels: 스타일링

#402 크루, 게스트 모집 상세 페이지 버튼 렌더링 로직 고도화 및 툴팁 기능
  src/pages/CrewsDetailPage/CrewsDetailPage.styles.ts
  src/pages/CrewsDetailPage/CrewsDetailPage.tsx
  src/pages/CrewsDetailPage/ParticipateButton.tsx
  src/pages/GamesDetailPage/GamesDetailPage.styles.ts
  src/pages/GamesDetailPage/GamesDetailPage.tsx
  src/pages/GamesDetailPage/ParticipateButton.tsx
  src/pages/GamesDetailPage/components/BottomButton.tsx
  src/pages/GamesDetailPage/components/GuestButton.tsx
  src/pages/GamesDetailPage/components/HostButton.tsx
  src/type/api/member.ts
Labels: 기능

#404 알림 아이템 시간 표기 수정
  src/components/NotificationItem/NotificationItem.tsx
Labels: 버그

#407 포지션 설명 토스트 구현 및 정보 입력 페이지 포지션 설명 추가
  src/components/shared/ToggleButton/ToggleButtons.hook.ts
  src/consts/positions.ts
  src/hooks/usePositionToast.tsx
  src/pages/ProfilePage/Profile.tsx
  src/pages/RegisterPage/RegisterPage.tsx
Labels: 기능, 버그

#406 알림 목록 쿼리 getNextPageParam 수정
  src/hooks/queries/useAlarmsQuery.ts
Labels: 버그

#411 크루 생성 페이지 폰트 깨지는 문제
  src/pages/CreateCrewPage/consts/createCrewOptions.ts
Labels: 긴급, 버그, D-0

#413 게스트 매치 생성 페이지 스켈레톤 ui key prop 추가
  src/pages/CreateGamePage/CreateGamePageSkeleton/CreateGamePageSkeleton.styles.ts
  src/pages/CreateGamePage/CreateGamePageSkeleton/CreateGamePageSkeleton.tsx
Labels: 긴급, 버그, D-0

#417 EventSource 로직 수정
  src/App.tsx
  src/ConnectSSE.tsx
  src/hooks/useEventSource.ts
  src/pages/NotificationPage/NotificationPage.tsx
  src/pages/NotificationPage/components/CrewNotificationItem/CrewNotificationItem.tsx
  src/pages/NotificationPage/components/GameNotificationItem/GameNotificationItem.tsx
  src/routes/router.tsx
Labels: 기능

#423 모두 지우기 버튼 스타일 수정
  src/pages/NotificationPage/NotificationPage.styles.ts
  src/pages/NotificationPage/NotificationPage.tsx
Labels: 스타일링, D-0

#416 메인페이지 ui 개선: 크루 랭킹 추가 및 게스트, 크루 존재하지 않을때의 분기처리
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/MainPageNoContentItem.tsx
Labels: 기능, D-1
